// GENERATED FILE — replace by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// DO NOT edit this file manually. The values below are placeholders.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions: unsupported platform. '
            'Run `flutterfire configure` to regenerate this file.');
    }
  }

  // ── Replace these with values from `flutterfire configure` ────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5pV4AeHo-QGX4N2p9zO-Y_0mrdxAp2M',
    appId: '1:548762911232:ios:cbad5474cf1f2e940a0ee5',
    messagingSenderId: '548762911232',
    projectId: 'mydays-84ed9',
    storageBucket: 'mydays-84ed9.firebasestorage.app',
    iosBundleId: 'com.mydays.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDIJ69e_i3yxhm4YVrh8MDoGd1WNHjRFM',
    appId: '1:548762911232:web:61398c691187f6c60a0ee5',
    messagingSenderId: '548762911232',
    projectId: 'mydays-84ed9',
    authDomain: 'mydays-84ed9.firebaseapp.com',
    storageBucket: 'mydays-84ed9.firebasestorage.app',
    measurementId: 'G-ESZV96P2Z9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDIJ69e_i3yxhm4YVrh8MDoGd1WNHjRFM',
    appId: '1:548762911232:web:61398c691187f6c60a0ee5',
    messagingSenderId: '548762911232',
    projectId: 'mydays-84ed9',
    authDomain: 'mydays-84ed9.firebaseapp.com',
    storageBucket: 'mydays-84ed9.firebasestorage.app',
    measurementId: 'G-ESZV96P2Z9',
  );

}